#!/usr/bin/perl
# Twitch MP3 tagger.
# Copyright (c) 2023-2026, Rev. Duncan Ross Palmer (2E0EOL)
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
#
#     * Redistributions of source code must retain the above copyright notice,
#       this list of conditions and the following disclaimer.
#
#     * Redistributions in binary form must reproduce the above copyright
#       notice, this list of conditions and the following disclaimer in the
#       documentation and/or other materials provided with the distribution.
#
#     * Neither the name of the the maintainer, nor the names of its contributors
#       may be used to endorse or promote products derived from this software
#       without specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
# AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
# ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE
# LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
# CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
# SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
# INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
# CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
# ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
# POSSIBILITY OF SUCH DAMAGE.

package Daybo::Twitch::Retag;
use English qw(-no_match_vars);
use File::Spec;
use Moose;

our $VERSION = '0.2.0';

our $URL = 'https://git.sr.ht/~m6kvm/twitch-tag-mp3';

has 'jobs'    => (is => 'ro', isa => 'Int',  default => 1);
has 'noop'    => (is => 'ro', isa => 'Bool', default => 0);
has 'verbose' => (is => 'ro', isa => 'Bool', default => 0);

my @pids;

sub run {
	my ($self, $dirname) = @_;
	my $filename;
	local *dirHandle;

	if (!opendir(dirHandle, $dirname)) {
		print "Can\'t open $dirname, ignoring\n";
		return 0;
	}

	while ($filename = readdir(dirHandle)) {
		next if ($filename eq '.' || $filename eq '..');
		my $relPath = $dirname . '/' . $filename;
		if (-d $relPath) {
			if (acceptableDirName($filename)) {
				$self->log("chdir $relPath");
				$self->run($relPath);
			}
		} else {
			if (open(FILEHANDLE, '<' . $relPath)) {
				my $ext;

				$ext = getExt($filename);
				close(FILEHANDLE);

				if (isMp3($ext)) {
					$self->log("Tagging $relPath");
					$self->tag(
						$relPath,
						parseFileName($filename),
					);
				}
			}
		}
	}

	closedir(dirHandle);

	foreach my $pid (@pids) {
		waitpid($pid, 0);
	}

	return 0;
}

sub log {
	my ($self, $msg) = @_;
	print "$msg\n" if ($self->verbose);
	return;
}

sub usage {
	printf("twitch-tag-mp3 %s usage:\n", $VERSION);
	print("twitch-tag-mp3.pl <base_dir>\n\n");
	print("See README for more information, or $URL\n");
	return 1;
}

sub isMp3 {
	my $ext = $_[0];
	return (defined($ext) && lc($ext) eq 'mp3');
}

sub getExt {
	my $fn = $_[0];
	my @arr;
	my $ext;

	@arr = split(m/\./, $fn);
	$ext = $arr[scalar(@arr)-1];
	return undef if ($fn eq $ext);
	return $ext;
}

sub tag {
	my ($self, $file, $artist, $album, $track, $year) = @_;

	if (scalar(@pids) >= $self->jobs) {
		my $done = waitpid(-1, 0);
		@pids = grep { $_ != $done } @pids;
	}

	my $pid = fork();
	die("Cannot fork! $ERRNO") unless (defined($pid));

	if ($pid) { # parent
		push(@pids, $pid);
	} else { # child
		$0 = sprintf("tagging '%s'", $file);
		$self->tagPerProcess($file, $artist, $album, $track, $year);
		exit(0);
	}
}

sub tagPerProcess {
	my ($self, $file, $artist, $album, $track, $year) = @_;

	$self->log("artist: $artist, album: $album, track: $track, year: $year");

	return if ($self->noop);

	__system('id3v2', '--delete-all', $file);
	__system(
		'id3v2',
		'--artist', $artist,
		'--album',  $album,
		'--song',   $track,
		'--year',   $year,
		'--comment', "Generated by twitch-tag-mp3 $VERSION - $URL",
		$file,
	);

	return;
}

sub __system {
	my (@args) = @_;

	open(my $null_fh, '>', File::Spec->devnull())
	    or die("Can't open null device: $ERRNO");

	open(my $save_stdout, '>&', \*STDOUT)
	    or die("Can't dup STDOUT: $ERRNO");
	open(my $save_stderr, '>&', \*STDERR)
	    or die("Can't dup STDERR: $ERRNO");

	open(STDOUT, '>&', $null_fh)
	    or die("Can't redirect STDOUT: $ERRNO");
	open(STDERR, '>&', $null_fh)
	    or die("Can't redirect STDERR: $ERRNO");

	system(@args);

	my $exitCode = $CHILD_ERROR;

	open(STDOUT, '>&', $save_stdout)
	    or die("Can't restore STDOUT: $ERRNO");
	open(STDERR, '>&', $save_stderr)
	    or die("Can't restore STDERR: $ERRNO");

	if ($exitCode == -1) {
		die("Failed to run id3v2: $ERRNO");
	} elsif ($exitCode != 0) {
		die(sprintf('id3v2 exited with status %d', $exitCode >> 8));
	}

	return $exitCode;
}

sub parseFileName {
	# Example: '1stdegreeproductions (live) 2021-10-18 11_05-40110166187.mp3'
	my ($filename) = @_;
	if ($filename =~ m/^(\w+)\s\(\w+\)\s(\d{4})-\d{2}-\d{2}.*/) {
		my ($artist, $album, $track, $year) = ($1, undef, undef, $2);
		my $artistRaw = $artist;

		$track = $filename;
		$track =~ s/\.mp3$//;
		$track =~ s/-trim//;
		$track =~ s/-desilence//;
		$track =~ s/-tempo//;
		$track =~ s/-untempo//;
		$track =~ s/-keep//;

		$artist =~ s/Official//gi;
		$artist =~ s/Music//gi;
		$artist = 'Raymond Doyle' if ($artist eq 'CarteBlanche88');
		$artist = 'Taucher' if (lc($artist) eq 'taucher66');
		$artist = 'Kristina Sky' if ($artist eq 'TheRealKristinaSky');
		$artist = 'Edit' if ($artist eq 'The_Real_DJ_Edit' || $artist eq 'TheReal_DJEdit');
		$artist = 'Vlastimil' if ($artist eq 'VlastimilVibes');
		$artist =~ s/dj//i;
		$artist =~ s/_/ /g;
		$artist =~ s/\s*$//;
		$artist =~ s/^\s*//;

		if ($artist =~ /^[A-Z]{2,}/ || $artist =~ /[a-z][A-Z]/) {
			my @words = ($artist =~ /([A-Z][a-z]+|[A-Z]+|[a-z]+|[0-9]+)/g);
			$artist = join(' ', map { ucfirst(lc($_)) } @words);
		}

		$artist =~ s/\b([a-z])/uc($1)/ge;
		$track =~ s/^([a-z])/uc($1)/e;

		$artist = 'DJ Edit' if ($artist eq 'Edit');
		$artist = 'DJ Paulo' if ($artist eq 'Paulo');
		$artist = 'DJ Baedine' if ($artist eq 'Baedine');
		$artist = $artistRaw if ($artistRaw =~ /TV$/);

		$album = "${artist} on Twitch";

		return ($artist, $album, $track, $year);
	}

	die("Cannot parse filename structure: '$filename'");
}

sub acceptableDirName {
	my ($dirName) = @_;
	return ($dirName ne '@eaDir');
}

1;
