#!/usr/bin/env bash
# Twitch MP3 tagger.
# Copyright (c) 2023-2026, Rev. Duncan Ross Palmer (2E0EOL)
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
#
#     * Redistributions of source code must retain the above copyright notice,
#       this list of conditions and the following disclaimer.
#
#     * Redistributions in binary form must reproduce the above copyright
#       notice, this list of conditions and the following disclaimer in the
#       documentation and/or other materials provided with the distribution.
#
#     * Neither the name of the the maintainer, nor the names of its contributors
#       may be used to endorse or promote products derived from this software
#       without specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
# AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
# ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE
# LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
# CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
# SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
# INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
# CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
# ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
# POSSIBILITY OF SUCH DAMAGE.

set -euo pipefail

. inc/setUp.sh

perl "-I${LIBDIR}" "${EXE}" -d "${rootDir}"

eval "$(
id3v2 --list-rfc822 "${rootDir}/Ucron (live) 2022-10-17 00_06-40358894505-desilence.mp3" |
awk -F': ' '
$1=="TPE1" {print "artist=\"" $2 "\""}
$1=="TALB" {print "album=\"" $2 "\""}
$1=="TIT2" {print "track=\"" $2 "\""}
$1=="TYER" {print "year=\"" $2 "\""}
$1=="COMM" {val=$0; sub(/^COMM[^:]*: /, "", val); sub(/^\([^)]*\)\[[^\]]*\]: ?/, "", val); print "comment=\"" val "\""}
'
)"

check() {
	local field="$1" expected="$2" actual="$3"
	if [[ "$actual" != "$expected" ]]; then
		echo "FAIL $field: expected \"$expected\", got \"$actual\""
		exit 2
	fi
	echo "OK $field: $actual"
}

check artist  "Ucron"                                            "$artist"
check album   "Ucron on Twitch"                                  "$album"
check track   "Ucron 2022-10-17 00:06:00 40358894505"           "$track"
check year    "2022"                                             "$year"
check comment "Generated by github.com/daybologic/twitch-tag-mp3" "$comment"

exit 0
